### ISSUE TITLE
Hello, how can I open the webpage without Google Auth?

### ISSUE THREAD

**Issue by TsinghuaSIGS** [JesseKartabani/chat-gpt-enhanced#4]
I want to set up a site that don't need to login.
Thanks

Best wishes.

**Comment by JesseKartabani** [comment]
@TsinghuaSIGS 

Sorry for the late reply, if your still wondering how to do this the easiest way would be reverting to an older commit before I added google auth. Only issue is you lose a lot of style changes and features doing that.

If you don't want to do that you'd have to delete a fair bit of code by hand as most components are only displayed if a user is logged in or subscribed.
